server:
  port: 8081
spring:
  application:
    name: game-keeper
kafka:
  bootstrap-servers: kafka:9092
  topics:
    metrics: device-metrics
    device-states: device-states
    game-states: game-states
  consumer:
    group-id: gkeeper-group
  streams:
    application-id: game-keeper-application
    output-topic: gkeeper-output-topic
